USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/cross/cross77_3776/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a9
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
ARCH_ARM_HAVE_VFP := true

TARGET_BOOTLOADER_BOARD_NAME := cross77_3776

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
INTERNAL_BOOTIMAGE_ARGS += --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --second_offset 0x00f00000 --tags_offset 0x00000100 --board 1371811777

# fix this up by examining /proc/mtd on a running device
# For mediatek based devices, the file is /proc/dumchar_info
BOARD_BOOTIMAGE_PARTITION_SIZE := 6291456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 6291456
BOARD_SECROIMAGE_PARTITION_SIZE := 6291456
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 629145600
BOARD_CACHEIMAGE_PARTITION_SIZE := 537919488
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_FLASH_BLOCK_SIZE := 2048
TARGET_USERIMAGES_USE_EXT4 := true

TARGET_PREBUILT_KERNEL := device/cross/cross77_3776/kernel

BOARD_CUSTOM_BOOTIMG_MK := device/cross/cross77_3776/boot.mk

BOARD_HAS_NO_SELECT_BUTTON := true

# cm recovery stuff
BOARD_RECOVERY_SWIPE := 1

# twrp recovery stuff
# remove unneeded features to make the generated image smaller.
DEVICE_RESOLUTION := 540x960
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_REBOOT_BOOTLOADER := true
TW_NO_USB_STORAGE := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true
TW_EXCLUDE_SUPERSU := true
TWHAVE_SELINUX := false
TW_NO_EXFAT := true
TW_NO_EXFAT_FUSE := true

